"""Shard statistics report (CLAUDE.md D5: rows, fraud count, fraud rate, feature summary per bank)."""
import json
from pathlib import Path

import pandas as pd


def _bank_summary(df: pd.DataFrame) -> dict:
    n_rows = len(df)
    n_fraud = int(df["Class"].sum())
    return {
        "n_rows": n_rows,
        "n_fraud": n_fraud,
        "n_legit": n_rows - n_fraud,
        "fraud_rate_pct": round(100 * n_fraud / n_rows, 4) if n_rows else 0.0,
        "amount_mean": round(float(df["Amount"].mean()), 2) if n_rows else None,
        "amount_std": round(float(df["Amount"].std()), 2) if n_rows else None,
    }


def build_report(shards: dict[str, pd.DataFrame], holdout: pd.DataFrame, seed: int) -> dict:
    return {
        "seed": seed,
        "banks": {bank: _bank_summary(df) for bank, df in shards.items()},
        "global_holdout": _bank_summary(holdout),
    }


def write_report(report: dict, json_path: Path, markdown_path: Path) -> None:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    lines = [
        "# Phase 1 shard statistics report",
        "",
        f"Seed: `{report['seed']}`. Generated by `ml/partition/run_partition.py`. "
        "Proposed shard sizes - pending explicit approval per CLAUDE.md D5.",
        "",
        "| Bank | Rows | Fraud rows | Legit rows | Fraud rate | Amount mean | Amount std |",
        "|---|---|---|---|---|---|---|",
    ]
    for bank, s in report["banks"].items():
        lines.append(
            f"| {bank} | {s['n_rows']} | {s['n_fraud']} | {s['n_legit']} | "
            f"{s['fraud_rate_pct']}% | {s['amount_mean']} | {s['amount_std']} |"
        )
    h = report["global_holdout"]
    lines.append(
        f"| Global holdout | {h['n_rows']} | {h['n_fraud']} | {h['n_legit']} | "
        f"{h['fraud_rate_pct']}% | {h['amount_mean']} | {h['amount_std']} |"
    )
    lines.append("")
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.write_text("\n".join(lines), encoding="utf-8")
